[DEFAULT]
# Work directly in your Semester folder
working_dir = /home/ubuntu/Nextcloud/SS26

# Keep any local-only files you add yourself, still update changed remote files
on_conflict = no-delete

# Helpful logs
report = yes
status = yes
show_not_deleted = yes

# Pick up remote changes without unnecessary downloads
redownload = always-smart

# Be gentle to ILIAS
tasks = 3
downloads = 3
task_delay = 0.1

[auth:ilias]
type = credential-file
path = /home/ubuntu/pferd/.pferd_pass

[auth:tfa]
type = tfa

[crawl:KIT-ILIAS]
type = kit-ilias-web
auth = auth:ilias
tfa_auth = auth:tfa
target = desktop
output_dir = .
links = plaintext

# Rename long course titles to short names
transform =
  # Rename course root folders
  ".*0133000 – Höhere Mathematik I.*" -name-re-> HM-1
  ".*Mathematik I e.*" -name-re-> HM-1-MINT
  ".*0186800 – Höhere Mathematik II.*" -name-re-> HM-2
  ".*Betriebssysteme.*" -name-re-> Betriebssysteme
  ".*Programmierparadigmen.*" -name-re-> Propa
  ".*Quantum Machine Learning.*" -name-re-> Quantum-ML
  ".*Numerische Mathematik.*" -name-re-> Numerik
  ".*Physik I.*" -name-re-> Physik-1-Info
  ".*Informationssicherheit.*" -name-re-> Infosec
  ".*Informationssicherheit.*" -name-re-> Infosec
  ".*Einführung in die Spieltheorie.*" -name-re-> Lasse/Spieltheorie
  ".*Volkswirtschaftslehre II.*" -name-re-> Lasse/Volkswirtschaftslehre-2
  ".*Mathematik II e.*" -name-re-> HM-2-MINT
