[DEFAULT]
# Work directly in your WS25 folder
working_dir = /home/ubuntu/Nextcloud/WS25

# Keep any local-only files you add yourself, still update changed remote files
on_conflict = no-delete

# Helpful logs
report = yes
status = yes
show_not_deleted = yes

# Pick up remote changes without unnecessary downloads
redownload = always-smart

# Be gentle to ILIAS
tasks = 1
downloads = 1
task_delay = 0.2

[auth:ilias]
type = credential-file
path = /home/ubuntu/pferd/.pferd_pass

[auth:tfa]
type = tfa

[crawl:KIT-ILIAS]
type = kit-ilias-web
auth = auth:ilias
tfa_auth = auth:tfa
target = desktop
output_dir = .
links = plaintext

# Rename long course titles to short names
transform =
  # Rename course root folders
  ".*Grundlagen der Wahrscheinlichkeitstheorie.*" -name-re-> Grundlagen-WST
  ".*Höhere Mathematik II.*" -name-re-> Höhere-Mathematik-2
  ".*ICPC.*" -name-re-> ICPC
  ".*Grundlagen der künstlichen Intelligenz.*" -name-re-> Grundlagen-KI
  ".*Digitaltechnik.*" -name-re-> Digitaltechnik
  ".*Betriebssysteme.*" -name-re-> Betriebssysteme
  ".*Programmierparadigmen.*" -name-re-> Propa
  ".*Basispraktikum Lego Mindstorms.*" -name-re-> Lego-Mindstorm
  ".*Höhere Mathematik I.*" -name-re-> Höhere-Mathematik-1
  ".*Rechnerorganisation.*" -name-re-> Rechnerorganisation
  ".*Volkswirtschaftslehre I.*" -name-re-> Volkswirtschaftslehre-1
  ".*Mathematik I e.*" -name-re-> MINT-HM1

