[DEFAULT]
working_dir = /home/ubuntu/Nextcloud/__SEMESTER__

on_conflict = no-delete
report = yes
status = yes
show_not_deleted = yes
redownload = always-smart

tasks = 1
downloads = 1
task_delay = 0.1

[auth:ilias]
type = credential-file
path = /home/ubuntu/pferd/.pferd_pass

[auth:tfa]
type = tfa

[crawl:KIT-ILIAS]
type = kit-ilias-web
auth = auth:ilias
tfa_auth = auth:tfa
target = desktop
output_dir = .
links = plaintext

transform =
  # Add semester-specific rename rules here
